"""Structured feedback / report generation.

Assembles the final interview report from aggregated scores and the session
context, and persists it for retrieval. Reporting is deterministic (thresholds
over per-topic averages plus recurring missing concepts); when Gemini is enabled
and a PromptBuilder is wired, the narrative (summary, strengths, improvements,
next steps) is generated by Gemini and grounded in the same session context,
falling back to the deterministic report on any failure.

Collaborators: EvaluationEngine, ScoreRepository, FeedbackRepository,
SessionRepository, GeminiService, PromptBuilder.
"""

from __future__ import annotations

from collections import Counter

from app.database.repositories.feedback_repository import FeedbackRepository
from app.database.repositories.score_repository import ScoreRepository
from app.database.repositories.session_repository import SessionRepository
from app.models.common import new_uuid, utc_now
from app.models.feedback import FeedbackRead, TopicSummary
from app.services.evaluation_engine import EvaluationEngine
from app.services.gemini_service import GeminiService
from app.services.prompt_builder import FEEDBACK_SCHEMA, PromptBuilder
from app.utils.errors import NotFoundError, ValidationError
from app.utils.logging import get_logger

logger = get_logger(__name__)

#: Topic averages at/above this count as a strength.
STRENGTH_THRESHOLD = 6.5
#: Topic averages below this count as a gap.
GAP_THRESHOLD = 5.0
#: How many recurring missing concepts to surface in the report.
MAX_MISSING_CONCEPTS = 3
#: Source labels persisted on the report row.
AI_SOURCE = "ai"
DETERMINISTIC_SOURCE = "deterministic"
#: Prefix used to stash AI next steps inside ``improvements`` for the API map.
NEXT_STEP_PREFIX = "Next: "


class FeedbackGenerator:
    """Produces the final structured interview report."""

    def __init__(
        self,
        evaluation_engine: EvaluationEngine,
        score_repository: ScoreRepository,
        feedback_repository: FeedbackRepository,
        gemini_service: GeminiService,
        session_repository: SessionRepository,
        prompt_builder: PromptBuilder | None = None,
    ) -> None:
        self._evaluator = evaluation_engine
        self._scores = score_repository
        self._feedback = feedback_repository
        self._gemini = gemini_service
        self._sessions = session_repository
        self._builder = prompt_builder

    def generate_report(self, session_id: str) -> FeedbackRead:
        """Build and persist the full report for a session.

        Deterministic: aggregates the session's recorded scores per topic,
        derives strengths/gaps from threshold averages, and appends the most
        frequently missed concepts to the improvements list. When Gemini is
        enabled the narrative is layered on via ``_try_ai_feedback``; any
        failure keeps the deterministic content intact.
        """
        session = self._sessions.get_by_id(session_id)
        if session is None:
            raise NotFoundError(f"Session {session_id} not found")

        context = self._sessions.loads_json(session.get("context"), {})
        scores = self._scores.list_by_session(session_id)
        topic_titles = {topic.get("id"): topic.get("title", "") for topic in context.get("topics", [])}

        topic_scores: dict[str, list[float]] = {}
        for row in scores:
            topic_scores.setdefault(row["topic_id"], []).append(float(row["score"]))

        topic_summaries = [
            TopicSummary(
                topic_id=topic_id,
                title=topic_titles.get(topic_id, topic_id),
                average_score=round(sum(values) / len(values), 2),
            )
            for topic_id, values in topic_scores.items()
        ]

        all_scores = [float(row["score"]) for row in scores]
        overall = round(sum(all_scores) / len(all_scores), 2) if all_scores else 0.0

        strengths = [
            f"{topic.title} ({topic.average_score:.1f}/10)"
            for topic in topic_summaries
            if topic.average_score >= STRENGTH_THRESHOLD
        ]
        improvements = [
            f"{topic.title} ({topic.average_score:.1f}/10)"
            for topic in topic_summaries
            if topic.average_score < GAP_THRESHOLD
        ]
        improvements.extend(self._recurring_missing_concepts(context, MAX_MISSING_CONCEPTS))

        summary = (
            f"Interview complete: {len(scores)} answer(s) across "
            f"{len(topic_summaries)} topic(s) with an overall score of {overall:.1f}/10."
        )

        source = DETERMINISTIC_SOURCE
        ai_report = self._try_ai_feedback(session_id, context, scores, topic_summaries, overall)
        if ai_report is not None:
            summary = ai_report["summary"]
            strengths = ai_report["strengths"]
            improvements = ai_report["improvement_areas"] + [
                f"{NEXT_STEP_PREFIX}{step}" for step in ai_report["next_steps"]
            ]
            source = AI_SOURCE

        feedback_id = new_uuid()
        created_at = utc_now()
        self._feedback.create(
            feedback_id=feedback_id,
            session_id=session_id,
            overall_score=overall,
            summary=summary,
            strengths=strengths,
            improvements=improvements,
            topics=[topic.model_dump(mode="json") for topic in topic_summaries],
            created_at=created_at,
            source=source,
        )
        logger.info(
            "Generated report %s for session %s (overall %.2f, source=%s)",
            feedback_id,
            session_id,
            overall,
            source,
        )
        return FeedbackRead(
            id=feedback_id,
            session_id=session_id,
            overall_score=overall,
            summary=summary,
            strengths=strengths,
            improvements=improvements,
            topics=topic_summaries,
            created_at=created_at,
            source=source,
        )

    # --- AI narrative ---------------------------------------------------------

    def _try_ai_feedback(
        self,
        session_id: str,
        context: dict,
        scores: list[dict],
        topic_summaries: list[TopicSummary],
        overall: float,
    ) -> dict | None:
        """Return an AI-generated feedback payload, or ``None`` to keep deterministic.

        Called only when Gemini is enabled; every failure (disabled, no builder,
        LLM error, malformed or empty JSON) degrades gracefully to ``None`` so
        Gemini can never break report generation. An interview with no scored
        answers is never sent to the model.
        """
        if not self._gemini.enabled:
            return None
        if not scores:
            logger.info("Skipping AI feedback for %s: no scored answers.", session_id)
            return None
        if self._builder is None:
            logger.warning(
                "Gemini enabled but no prompt builder wired; using deterministic report for %s.",
                session_id,
            )
            return None
        try:
            payload = self._build_feedback_context(context, scores, topic_summaries, overall)
            prompt = self._builder.build_feedback_prompt(session_id=session_id, context=payload)
            result = self._gemini.generate_json(prompt, FEEDBACK_SCHEMA)
            report = self._normalize_feedback(result)
            if not report["summary"]:
                raise ValidationError("AI feedback response is missing an overall summary.")
            logger.info("AI feedback narrative generated for session %s", session_id)
            return report
        except Exception as exc:  # noqa: BLE001 - never let Gemini break reporting
            logger.warning(
                "AI feedback unavailable for %s; using deterministic report (%s)",
                session_id,
                type(exc).__name__,
            )
            return None

    def _build_feedback_context(
        self,
        context: dict,
        scores: list[dict],
        topic_summaries: list[TopicSummary],
        overall: float,
    ) -> dict:
        """Merge session context into the grounded context block for the prompt."""
        asked = {q.get("curriculum_question_id"): q for q in context.get("asked_questions", [])}
        answers = {a.get("question_id"): a for a in context.get("answers", [])}
        evaluations = []
        for evaluation in context.get("evaluations", []):
            question_id = evaluation.get("question_id")
            question = asked.get(question_id, {})
            answer = answers.get(question_id, {})
            evaluations.append(
                {
                    "question_id": question_id,
                    "topic_id": evaluation.get("topic_id", ""),
                    "kind": evaluation.get("kind", "primary"),
                    "question": question.get("text", ""),
                    "answer": answer.get("answer", ""),
                    "score": evaluation.get("score", 0),
                    "covered": list(evaluation.get("covered", []) or []),
                    "missing": list(evaluation.get("missing", []) or []),
                }
            )
        return {
            "candidate": context.get("analysis", {}),
            "topics": context.get("topics", []),
            "topic_summaries": [topic.model_dump(mode="json") for topic in topic_summaries],
            "overall_score": overall,
            "evaluations": evaluations,
        }

    @staticmethod
    def _normalize_feedback(result: dict) -> dict:
        """Convert the raw Gemini payload into a clean feedback report dict."""
        return {
            "summary": str(result.get("overall_summary") or "").strip(),
            "strengths": FeedbackGenerator._clean_strings(result.get("strengths")),
            "improvement_areas": FeedbackGenerator._clean_strings(result.get("improvement_areas")),
            "next_steps": FeedbackGenerator._clean_strings(result.get("next_steps")),
        }

    @staticmethod
    def _clean_strings(values) -> list[str]:
        """Return non-blank string items from ``values`` (or an empty list)."""
        if not isinstance(values, list):
            return []
        cleaned = []
        for value in values:
            text = str(value).strip()
            if text:
                cleaned.append(text)
        return cleaned

    @staticmethod
    def _recurring_missing_concepts(context: dict, limit: int) -> list[str]:
        """Return the most frequently missed concepts across the session."""
        counter: Counter[str] = Counter()
        for evaluation in context.get("evaluations", []):
            counter.update(evaluation.get("missing", []))
        return [f"Review: {concept}" for concept, _ in counter.most_common(limit)]
